name: Tests

on:
  push:
    branches: [main, release, packaging]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '0 0 * * 0'


jobs:
  Linter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install .[testing]

  Library:
    needs: [Linter]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', "3.10"]
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest] macos fails test in CUBDataset: 
        # def get_concept_categories(self) -> dict[str, list]: E   TypeError: 'type' object is not subscriptable
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install --upgrade torch
            pip install --upgrade torchvision
            pip install -r requirements.txt
            pip install pytest
            pip install .[testing]
      - name: Test with pytest
        run: pytest -vvv